# Cleaning Raw Data

This notebook contains **basic data cleaning steps for the Comments collected from reddit posts**.

In [50]:
# import libraries
import pandas as pd
pd.options.display.max_columns = 50
# packages for data cleaning function
import re
import string

## Load data

In [51]:
lib_df = pd.read_csv("C:/Users/samik/Downloads/SMM/Paper2/LiberalsData/Comments1.csv")
con_df = pd.read_csv("C:/Users/samik/Downloads/SMM/Paper2/ConservativesData/Comments1.csv")

In [52]:
lib_df.head()

,Author,Text,Date,Score
0,EndsWithJusSayin,>press secretary Karoline Leavitt told reporte...,2025-03-06 15:11:45+00:00,19805
1,SillyGoatGruff,"Fuck him, fuck her, and fuck that. \n\nCanadia...",2025-03-06 16:44:50+00:00,2685
2,New_Zorgo39,USA has lost every credibility it once had. Se...,2025-03-06 15:11:03+00:00,1621
3,Revolutionary-Swan77,Relationship hasn’t been this bad with Canada ...,2025-03-06 16:49:26+00:00,453
4,overbarking,Chatty Cathy doll. Pull her string and she'll ...,2025-03-06 15:05:54+00:00,164

In [53]:
con_df.head()

,Author,Text,Date,Score
0,otakuzod,What is Trump’s endgame with this? Was there ...,2025-03-04 18:11:52+00:00,434
1,[deleted],The White House needs to explain the reasoning...,2025-03-04 18:37:14+00:00,159
2,Communalbuttplug,Trumps just announced for every retaliatory ta...,2025-03-04 18:00:06+00:00,195
3,[deleted],I just don't know why it's necessary to pick f...,2025-03-04 18:52:01+00:00,158
4,Lifeisagreatteacher,Math:\n\nCanada annual trade surplus with US $...,2025-03-04 18:11:19+00:00,271

## Cleaning `comments` column

In [54]:
# copying new `clean_df` and cleaning up the tweetscomments
clean_lib_df = lib_df.copy()
clean_con_df = con_df.copy()

In [55]:
clean_lib_df.head()

,Author,Text,Date,Score
0,EndsWithJusSayin,>press secretary Karoline Leavitt told reporte...,2025-03-06 15:11:45+00:00,19805
1,SillyGoatGruff,"Fuck him, fuck her, and fuck that. \n\nCanadia...",2025-03-06 16:44:50+00:00,2685
2,New_Zorgo39,USA has lost every credibility it once had. Se...,2025-03-06 15:11:03+00:00,1621
3,Revolutionary-Swan77,Relationship hasn’t been this bad with Canada ...,2025-03-06 16:49:26+00:00,453
4,overbarking,Chatty Cathy doll. Pull her string and she'll ...,2025-03-06 15:05:54+00:00,164

In [56]:
clean_con_df.head()

,Author,Text,Date,Score
0,otakuzod,What is Trump’s endgame with this? Was there ...,2025-03-04 18:11:52+00:00,434
1,[deleted],The White House needs to explain the reasoning...,2025-03-04 18:37:14+00:00,159
2,Communalbuttplug,Trumps just announced for every retaliatory ta...,2025-03-04 18:00:06+00:00,195
3,[deleted],I just don't know why it's necessary to pick f...,2025-03-04 18:52:01+00:00,158
4,Lifeisagreatteacher,Math:\n\nCanada annual trade surplus with US $...,2025-03-04 18:11:19+00:00,271

In [57]:
import re
import string

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)       # remove URLs
    text = re.sub(r"\b(?:https?|ftp):\/\/\S+\b", "", text)    # extra safety
    text = re.sub(r"[^\w\s!?]", "", text)                       # keep ! and ? for VADER
    text = re.sub(r"\s+", " ", text).strip()                    # remove extra spaces
    return text

round1 = lambda x: clean_text(x)

In [58]:
# appling data cleaning function to `Text` column
clean_lib_df['Text'] = clean_lib_df['Text'].apply(round1)
clean_con_df['Text'] = clean_con_df['Text'].apply(round1)

In [59]:
import os
# Save cleaned file
output_path1 = "C:/Users/samik/Downloads/SMM/Paper2/LiberalsData/Preprocessed_Lib_Comments.csv.csv"
os.makedirs(os.path.dirname(output_path1), exist_ok=True)
clean_lib_df.to_csv(output_path1, index=False)

output_path2 = "C:/Users/samik/Downloads/SMM/Paper2/ConservativesData/Preprocessed_Con_Comments.csv"
os.makedirs(os.path.dirname(output_path2), exist_ok=True)
clean_con_df.to_csv(output_path2, index=False)

print(f"Cleaned file saved to: {output_path1}")
print(f"Cleaned file saved to: {output_path2}")

Cleaned file saved to: C:/Users/samik/Downloads/SMM/Paper2/LiberalsData/Preprocessed_Lib_Comments.csv.csv
Cleaned file saved to: C:/Users/samik/Downloads/SMM/Paper2/ConservativesData/Preprocessed_Con_Comments.csv

In [60]:
# checking that it worked
clean_lib_df.head()

,Author,Text,Date,Score
0,EndsWithJusSayin,press secretary karoline leavitt told reporter...,2025-03-06 15:11:45+00:00,19805
1,SillyGoatGruff,fuck him fuck her and fuck that canadians will...,2025-03-06 16:44:50+00:00,2685
2,New_Zorgo39,usa has lost every credibility it once had ser...,2025-03-06 15:11:03+00:00,1621
3,Revolutionary-Swan77,relationship hasnt been this bad with canada s...,2025-03-06 16:49:26+00:00,453
4,overbarking,chatty cathy doll pull her string and shell sa...,2025-03-06 15:05:54+00:00,164

In [61]:
clean_con_df.head()

,Author,Text,Date,Score
0,otakuzod,what is trumps endgame with this? was there so...,2025-03-04 18:11:52+00:00,434
1,[deleted],the white house needs to explain the reasoning...,2025-03-04 18:37:14+00:00,159
2,Communalbuttplug,trumps just announced for every retaliatory ta...,2025-03-04 18:00:06+00:00,195
3,[deleted],i just dont know why its necessary to pick fig...,2025-03-04 18:52:01+00:00,158
4,Lifeisagreatteacher,math canada annual trade surplus with us 108 b...,2025-03-04 18:11:19+00:00,271

In [62]:
# checking for missing values
clean_lib_df.isnull().sum()

Author    0
Text      0
Date      0
Score     0
dtype: int64

In [63]:
# checking for missing values
clean_con_df.isnull().sum()

Author    0
Text      0
Date      0
Score     0
dtype: int64